apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: # change link github argocd
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
