server_start = <<-SHELL
  sudo su
  export INSTALL_K3S_EXEC="--flannel-iface=eth1 --write-kubeconfig-mode=644"
  curl -sfL https://get.k3s.io | sh -
  sleep 10
  cd /vagrant && kubectl apply -f .
  SHELL



Vagrant.configure("2") do |config|  
  config.vm.box = "generic/alpine319"
  
  config.vm.define "Server" do |server|
    server.vm.hostname = "Server"
    server.vm.network :private_network, ip: "192.168.56.110"
    server.vm.synced_folder "./confs", "/vagrant", type: "nfs", mount_options: ["vers=3,tcp"]
    server.vm.provider :libvirt do |v|
      v.cpus = 1
      v.memory = 1024
    end
    server.vm.provision :shell, :inline => server_start
  end

end
